// client/react-storeon/js/Login.jsx
import React from "react";
import useStoreon from "storeon/react";

export const Login = () => {
	const { dispatch, loginError } = useStoreon("loginError");
	const login = e => {
        e.preventDefault();
        dispatch("user/login", { username: e.target.querySelector('[type="text"]').value });
    }
	return <div style={{
        position: 'absolute',
        top: '50%',
        left: '50%',
        transform: 'translate(-50%, -50%)',
        textAlign: 'center'
    }}>
        <form onSubmit={login}>
            <input type="text" placeholder="Enter you login"/>
            <input type="submit" value="Enter"/>
        </form>
        <div style={{color: 'red'}}>{loginError}</div>
    </div>
}

// client/svelte/src/components/Login.svelte
<div class="login">
    <form on:submit="fire('submit', event)">
        <input type="text" placeholder="Enter you login"/>
        <input type="submit" value="Enter"/>
    </form>
    {#if $loginError}
    <div class="error">{$loginError}</div>
    {/if}
</div>

<style>
    .login {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        text-align: center;
    }
    .login .error {
        color: red;
    }
</style>
